### PR TITLE
Resolve core-object deprecation warnings.

### LINKED ISSUE #11: [DEPRECATION] overriding init without calling this._super
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (/Users/blimmer/code/webapps/my-app/node_modules/ember-cli-deploy-display-revisions/lib/scm-table.js:8:29)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (/Users/blimmer/code/webapps/my-app/node_modules/ember-cli-deploy-display-revisions/lib/legacy-table.js:6:29)
```

### PR DESCRIPTION
**Pull request by blimmer**
## What Changed & Why
Explain what changed and why.

## Related issues
Link to related issues in this or other repositories (if any)
Resolves #11.

## PR Checklist
- [x] Add tests (n/a)? deprecation seems too high up the stack to catch?
- [x] Add documentation (n/a)? not needed
- [x] Prefix documentation-only commits with [DOC]

## People
Mention people who would be interested in the changeset (if any)

### CODE REVIEW

**Comment by ghedamat** [comment]
thanks @blimmer !

**Comment by blimmer** [comment]
No problem @ghedamat - any chance to get a release for this? that yellow warning is coming up even when not deploying :-X

**Comment by ghedamat** [comment]
@blimmer done

can you test `0.2.2`? thanks

**Comment by blimmer** [comment]
thanks - confirmed fixed 🎉

**Pull request merged**
