### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by jrjohnson** [comment]
@lukemelia I'm pretty sure this just needs a CI restart to pass and should probably be merged as it is a security vulnerability found with `npm audit`.

**Comment by lukemelia** [comment]
Thanks @jrjohnson. I kicked the build.

**Comment by lukemelia** [comment]
Thanks @DanielRuf! Apologies for the delay.

**Comment by lukemelia** [comment]
Released as 1.0.1.

**Pull request merged**
